import markdown
import time
from datetime import date
from ai_engine import get_aggregated_news, summarize_with_ai
from push_wechat import wechat_client
from push_pushplus import send_pushplus
from styler import WeChatStyler

def main():
    print("🚀 === AI 每日新闻任务启动 ===")
    
    # --- 第一步：抓取与生成 ---
    print("\n1️⃣ 正在抓取 RSS 并生成 AI 摘要...")
    raw_content = get_aggregated_news()
    ai_content = summarize_with_ai(raw_content)
    
    if not ai_content:
        print("❌ 生成内容为空，终止任务。")
        return

    # --- 第二步：准备标题和日期 ---
    today_str = date.today().strftime("%Y-%m-%d")
    title = f"AI 每日早报 ({today_str})"
    
    # --- 第三步：推送到 PushPlus (个人通知) ---
    print("\n2️⃣ 正在推送到 PushPlus...")
    # PushPlus 支持 Markdown，直接发
    # send_pushplus(ai_content)
    
# --- 第四步：推送到微信公众号草稿箱 ---
    print("\n3️⃣ 正在推送到微信公众号草稿箱...")
    try:
        # 3.1 先转成原始 HTML
        raw_html = markdown.markdown(ai_content)
        
        # 3.2 【关键步骤】调用美化器
        print("🎨 正在进行排版美化...")
        styled_content = WeChatStyler.beautify(raw_html)
        
        # 3.3 添加底部的版权声明 (可选)
        final_content = f"""
        {styled_content}
        <br><br>
        <div style="text-align: center; color: #ccc; font-size: 12px; margin-top: 20px;">
            ———— Generated by AI Agent ————
        </div>
        """
        
        # 3.4 上传封面图 (保持不变)
        media_id = wechat_client.upload_cover_image("cover.jpg")
        
        # 3.5 新建草稿 (传入美化后的 content)
        wechat_client.add_draft(title, final_content, media_id)
        
    except Exception as e:
        print(f"❌ 微信公众号推送失败: {e}")

    print("\n✅ === 任务全部完成！请去公众号后台查看草稿 === ")

if __name__ == "__main__":
    main()